spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# 之后的填写mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
